Webquanlysanpham/Models/DonViTinh.cs
using System.ComponentModel.DataAnnotations;

namespace Webquanlysanpham.Models
{
    public class DonViTinh
    {
        [Key]
        public long ID { get; set; }

        public string MaDVT { get; set; }

        public string DVTinh { get; set; }
    }
}

Webquanlysanpham/Controllers/DonViTinhController.cs
using Microsoft.AspNetCore.Mvc;
using Webquanlysanpham.Data;
using Webquanlysanpham.Models;

namespace Webquanlysanpham.Controllers
{
    public class DonViTinhController : Controller
    {
        private readonly AppDbContext _db;
        public DonViTinhController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<DonViTinh> donViTinhsList = _db.donViTinhs;
            return View(donViTinhsList);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DonViTinh obj)
        {
            if (ModelState.IsValid)
            {
                _db.donViTinhs.Add(obj);
                _db.SaveChanges();
                TempData["Thanh cong"] = "Tao Thanh Cong";
                return RedirectToAction("Index");
            }
            return View(obj);

        }
        [HttpGet]
        public IActionResult Edit(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DonViTinhFromDb = _db.donViTinhs.Find(id);
            if (DonViTinhFromDb == null)
            {
                return NotFound();
            }
            return View(DonViTinhFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DonViTinh obj)
        {
            if (ModelState.IsValid)
            {
                _db.donViTinhs.Update(obj);
                _db.SaveChanges();
                TempData["Thanh cong"] = "Sua Thanh Cong";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DonViTinhFromDb = _db.donViTinhs.Find(id);
            if (DonViTinhFromDb == null)
            {
                return NotFound();
            }
            return View(DonViTinhFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(long? id)
        {
            var obj = _db.donViTinhs.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.donViTinhs.Remove(obj);
            _db.SaveChanges();
            TempData["Thanh cong"] = "Xoa Thanh Cong";
            return RedirectToAction("Index");


        }
    }
}

Webquanlysanpham/Views/DonViTinh/Create.cshtml
@model Webquanlysanpham.Models.DonViTinh

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DonViTinh</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaDVT" class="control-label"></label>
                <input asp-for="MaDVT" class="form-control" />
                <span asp-validation-for="MaDVT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DVTinh" class="control-label"></label>
                <input asp-for="DVTinh" class="form-control" />
                <span asp-validation-for="DVTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="DonViTinh" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
</div>

Webquanlysanpham/Views/DonViTinh/Delete.cshtml
@model DonViTinh
<form method="post" asp-action="Delete">
    <input asp-for="ID" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Xoa DVT</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="MaDVT"></label>
            <input asp-for=MaDVT disabled class="form-control" />
            <span asp-validation-for="MaDVT" class="text-danger"></span>
        </div>
                <div class="mb-3">
            <label asp-for="DVTinh"></label>
            <input asp-for=DVTinh disabled class="form-control" />
            <span asp-validation-for="DVTinh" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Xoa DVT</button>
        <a asp-controller="DonViTinh" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
    </div>
</form>

Webquanlysanpham/Views/DonViTinh/Edit.cshtml
@model DonViTinh
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Sua DVT</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="MaDVT"></label>
            <input asp-for=MaDVT class="form-control" />
            <span asp-validation-for="MaDVT" class="text-danger"></span>
        </div>
                <div class="mb-3">
            <label asp-for="DVTinh"></label>
            <input asp-for=DVTinh class="form-control" />
            <span asp-validation-for="DVTinh" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Sua DVT</button>
        <a asp-controller="DonViTinh" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
    </div>
</form>

Webquanlysanpham/Views/DonViTinh/Index.cshtml
@model IEnumerable<DonViTinh>
@{
    ViewData["Title"] = "Index";
}

@if(TempData["Thanh cong"] != null){

    <h2>@TempData["Thanh cong"]</h2>
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Danh Sach Don Vi Tinh</h2>
        </div>
        <div class="col-6">
            <a asp-controller="DonViTinh" asp-action="Create" class="btn btn-primary">Tao DVT</a>
        </div>
    </div>
</div>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Ma Don Vi Tinh
            </th>
            <th>
                Ten Don Vi Tinh
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.MaDVT
                </td>
                <td width="50%">
                    @obj.DVTinh
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="DonViTinh" asp-action="Edit" asp-route-id="@obj.ID" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                </td>
                                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="DonViTinh" asp-action="Delete" asp-route-id="@obj.ID" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>