Webquanlysanpham/Models/SanPham_NhaCungCap.cs
using System.ComponentModel.DataAnnotations;

namespace Webquanlysanpham.Models
{
    public class SanPham_NhaCungCap
    {
        [Key]
        public long ID { get; set; }

        public long? SanPhamID { get; set; }

        public long? NCCID { get; set; }
    }
}

Webquanlysanpham/Controllers/SanPham_NhaCungCapController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Webquanlysanpham.Data;
using Webquanlysanpham.Models;

namespace Webquanlysanpham.Controllers
{
    public class SanPham_NhaCungCapController : Controller
    {
        private readonly AppDbContext _db;
        public SanPham_NhaCungCapController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<SanPham_NhaCungCap> sanPhams_nhaCungCapList = _db.sanPham_NhaCungCaps;
            return View(sanPhams_nhaCungCapList);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Listnhacungcap = new SelectList(_db.nhaCungCaps.ToList(), "ID", "TenNCC");
            ViewBag.Listsanpham = new SelectList(_db.sanPhams.ToList(), "ID", "TenSP");           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SanPham_NhaCungCap model)
        {
            ViewBag.Listnhacungcap = new SelectList(_db.nhaCungCaps.ToList(), "ID", "TenNCC");
            ViewBag.Listsanpham = new SelectList(_db.sanPhams.ToList(), "ID", "TenSP");
            if (ModelState.IsValid)
            {
                
                _db.sanPham_NhaCungCaps.Add(model);
                _db.SaveChanges();
                TempData["Thanh cong"] = "Tao Thanh Cong";
                return RedirectToAction("Index");
            }


            return View("Index");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var SanPham_NhaCungCapFromDb = _db.sanPham_NhaCungCaps.Find(id);
            if (SanPham_NhaCungCapFromDb == null)
            {
                return NotFound();
            }
            ViewBag.Listnhacungcap = new SelectList(_db.nhaCungCaps.ToList(), "ID", "TenNCC");
            ViewBag.Listsanpham = new SelectList(_db.sanPhams.ToList(), "ID", "TenSP");
            return View(SanPham_NhaCungCapFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SanPham_NhaCungCap obj)
        {
            if (ModelState.IsValid)
            {
                _db.sanPham_NhaCungCaps.Update(obj);
                _db.SaveChanges();
                TempData["Thanh cong"] = "Sua Thanh Cong";
                return RedirectToAction("Index");
            }
            ViewBag.Listnhacungcap = new SelectList(_db.nhaCungCaps.ToList(), "ID", "TenNCC");
            ViewBag.Listsanpham = new SelectList(_db.sanPhams.ToList(), "ID", "TenSP");
            return View(obj);

        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var SanPham_NhaCungCapFromDb = _db.sanPham_NhaCungCaps.Find(id);
            if (SanPham_NhaCungCapFromDb == null)
            {
                return NotFound();
            }
            return View(SanPham_NhaCungCapFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(long? id)
        {
            var obj = _db.sanPham_NhaCungCaps.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.sanPham_NhaCungCaps.Remove(obj);
            _db.SaveChanges();
            TempData["Thanh cong"] = "Xoa Thanh Cong";
            return RedirectToAction("Index");


        }
    }
}

Webquanlysanpham/Views/SanPham_NhaCungCap/Create.cshtml
@model Webquanlysanpham.Models.SanPham_NhaCungCap
@{
    ViewBag.Title = "Create";

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="row">
    <div class="col-6">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })            
            <div class="form-group">
                @Html.LabelFor(model => model.SanPhamID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SanPhamID, (SelectList)ViewBag.Listsanpham, new { @class = "form-control"  })
                    @Html.ValidationMessageFor(model => model.SanPhamID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NCCID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.NCCID, (SelectList)ViewBag.Listnhacungcap, new { @id="Members", @class= "select2 form-select",  @multiple = "multiple"  })
                    @Html.ValidationMessageFor(model => model.NCCID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 form-button">
                    <input type="submit" value="Create" class="btn btn-primary btn-user btn-block" />
                </div>
            </div>

        </div>
    </div>
</div>
}

<div>
    <a asp-controller="SanPham_NhaCungCap" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css"/>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script type="text/javascript">
        $(function () { 
            //get the selectedmember from the hidden field.
            var selectedmembers = $("#selectedmemebers").val().split(",");
            //set the value in the dropdownlist.
            $("#Members").select2({
                multiple: true,
              });
              $('#Members').val(selectedmembers).trigger('change'); 
        });
    </script>
}

Webquanlysanpham/Views/SanPham_NhaCungCap/Delete.cshtml
@model SanPham_NhaCungCap
<form method="post" asp-action="Delete">
    <input asp-for="ID" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Xoa SP_NCC</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="SanPhamID"></label>
            <input asp-for=SanPhamID disabled class="form-control" />
            <span asp-validation-for="SanPhamID" class="text-danger"></span>
        </div>
                <div class="mb-3">
            <label asp-for="NCCID"></label>
            <input asp-for=NCCID disabled class="form-control" />
            <span asp-validation-for="NCCID" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Xoa DVT</button>
        <a asp-controller="SanPham_NhaCungCap" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
    </div>
</form>

Webquanlysanpham/Views/SanPham_NhaCungCap/Edit.cshtml
@model Webquanlysanpham.Models.SanPham_NhaCungCap
@{
    ViewBag.Title = "Edit";

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="row">
    <div class="col-6">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })            
            <div class="form-group">
                @Html.LabelFor(model => model.SanPhamID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SanPhamID, (SelectList)ViewBag.Listsanpham, new { @class = "form-control"  })
                    @Html.ValidationMessageFor(model => model.SanPhamID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NCCID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="hidden" value="NCCID"  id="selectedmemebers"/>
                    @Html.DropDownListFor(model => model.NCCID, (SelectList)ViewBag.Listnhacungcap, new { @id="Members", @class= "select2 form-select",  @multiple = "multiple"  })
                    @Html.ValidationMessageFor(model => model.NCCID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 form-button">
                    <input type="submit" value="Edit" class="btn btn-primary btn-user btn-block" />
                </div>
            </div>

        </div>
    </div>
</div>
}

<div>
    <a asp-controller="SanPham_NhaCungCap" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css"/>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script type="text/javascript">
        $(function () { 
            //get the selectedmember from the hidden field.
            var selectedmembers = $("#selectedmemebers").val().split(",");
            //set the value in the dropdownlist.
            $("#Members").select2({
                multiple: true,
              });
              $('#Members').val(selectedmembers).trigger('change'); 
        });
    </script>
}

Webquanlysanpham/Views/SanPham_NhaCungCap/Index.cshtml
@model IEnumerable<SanPham_NhaCungCap>
@{
    ViewData["Title"] = "Index";
}

@if(TempData["Thanh cong"] != null){

    <h2>@TempData["Thanh cong"]</h2>
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Danh Sach LuuTruSP_NCC</h2>
        </div>
        <div class="col-6">
            <a asp-controller="SanPham_NhaCungCap" asp-action="Create" class="btn btn-primary">Tao SP_NCC</a>
        </div>
    </div>
</div>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                San Pham
            </th>
            <th>
                Nha Cung Cap
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.SanPhamID
                </td>
                <td width="50%">
                    @obj.NCCID
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="SanPham_NhaCungCap" asp-action="Edit" asp-route-id="@obj.ID" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                </td>
                                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="SanPham_NhaCungCap" asp-action="Delete" asp-route-id="@obj.ID" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>