Webquanlysanpham/Models/NhaCungCap.cs
using System.ComponentModel.DataAnnotations;

namespace Webquanlysanpham.Models
{
    public class NhaCungCap
    {
        [Key]
        public long ID { get; set; }

        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
    }
}

Webquanlysanpham/Controllers/NhaCungCapController.cs
using Microsoft.AspNetCore.Mvc;
using Webquanlysanpham.Data;
using Webquanlysanpham.Models;

namespace Webquanlysanpham.Controllers
{
    public class NhaCungCapController : Controller
    {
        private readonly AppDbContext _db;
        public NhaCungCapController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<NhaCungCap> nhaCungCapsList = _db.nhaCungCaps;
            return View(nhaCungCapsList);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NhaCungCap obj)
        {
            if (ModelState.IsValid)
            {
                _db.nhaCungCaps.Add(obj);
                _db.SaveChanges();
                TempData["Thanh cong"] = "Tao Thanh Cong";
                return RedirectToAction("Index");
            }
            return View(obj);

        }
        [HttpGet]
        public IActionResult Edit(long? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var NhaCungCapFromDb = _db.nhaCungCaps.Find(id);
            if (NhaCungCapFromDb == null)
            {
                return NotFound();
            }
            return View(NhaCungCapFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NhaCungCap obj)
        {
            if (ModelState.IsValid)
            {
                _db.nhaCungCaps.Update(obj);
                _db.SaveChanges();
                TempData["Thanh cong"] = "Sua Thanh Cong";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var NhaCungCapFromDb = _db.nhaCungCaps.Find(id);
            if (NhaCungCapFromDb == null)
            {
                return NotFound();
            }
            return View(NhaCungCapFromDb);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.nhaCungCaps.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.nhaCungCaps.Remove(obj);
            _db.SaveChanges();
            TempData["Thanh cong"] = "Xoa Thanh Cong";
            return RedirectToAction("Index");

        }
    }
}

Webquanlysanpham/Views/NhaCungCap/Create.cshtml
@model NhaCungCap
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Tao NhaCungCap</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="TenNCC"></label>
            <input asp-for=TenNCC class="form-control" />
            <span asp-validation-for="TenNCC" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DiaChi"></label>
            <input asp-for=DiaChi class="form-control" />
            <span asp-validation-for="DiaChi" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SoDienThoai"></label>
            <input asp-for=SoDienThoai class="form-control" />
            <span asp-validation-for="SoDienThoai" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for=Email class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Tao NhaCungCap</button>
        <a asp-controller="NhaCungCap" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
    </div>
</form>

Webquanlysanpham/Views/NhaCungCap/Delete.cshtml
@model NhaCungCap
<form method="post" asp-action="Delete">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Xoa NhaCungCap</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="TenNCC"></label>
            <input asp-for=TenNCC disabled class="form-control" />
            <span asp-validation-for="TenNCC" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DiaChi"></label>
            <input asp-for=DiaChi disabled class="form-control" />
            <span asp-validation-for="DiaChi" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SoDienThoai"></label>
            <input asp-for=SoDienThoai disabled class="form-control" />
            <span asp-validation-for="SoDienThoai" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for=Email disabled class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Xoa NhaCungCap</button>
        <a asp-controller="NhaCungCap" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
    </div>
</form>

Webquanlysanpham/Views/NhaCungCap/Edit.cshtml
@model NhaCungCap
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Sua NhaCungCap</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="TenNCC"></label>
            <input asp-for=TenNCC class="form-control" />
            <span asp-validation-for="TenNCC" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DiaChi"></label>
            <input asp-for=DiaChi class="form-control" />
            <span asp-validation-for="DiaChi" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="SoDienThoai"></label>
            <input asp-for=SoDienThoai class="form-control" />
            <span asp-validation-for="SoDienThoai" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for=Email class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
  
        <button type="submit" class="btn btn-primary" style="width:150px">Sua NhaCungCap</button>
        <a asp-controller="NhaCungCap" asp-action="Index" class="btn btn-secondary" style="width:150px">Quay Lai</a>
    </div>
</form>

Webquanlysanpham/Views/NhaCungCap/Index.cshtml
@model IEnumerable<NhaCungCap>
@{
    ViewData["Title"] = "Index";
}

@if(TempData["Thanh cong"] != null){

    <h2>@TempData["Thanh cong"]</h2>
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Danh Sach Nha Cung Cap</h2>
        </div>
        <div class="col-6">
            <a asp-controller="NhaCungCap" asp-action="Create" class="btn btn-primary">Tao Nha Cung Cap</a>
        </div>
    </div>
</div>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Ten NCC
            </th>
            <th>
                Dia Chi
            </th>
            <th>
                So Dien Thoai
            </th>
            <th>
                Email
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.TenNCC
                </td>
                <td width="50%">
                    @obj.DiaChi
                </td>
                                <td width="50%">
                    @obj.SoDienThoai
                </td>
                                <td width="50%">
                    @obj.Email
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="NhaCungCap" asp-action="Edit" asp-route-id="@obj.ID" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    </div>
                </td>
                                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="NhaCungCap" asp-action="Delete" asp-route-id="@obj.ID" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>